### ISSUE TITLE
Call screensaver (Black) after the video end or video stopped

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#20]
Call screensaver (Black) function after the video end or video stopped

**Comment by rsmoorthy** [comment]
All the code is now written, so that the screensaver is called after the video end or video stopped.
However, this does not always work effectively. After the video is stopped or ended, kodi locks up for few seconds (8 seconds) for some reason and then only all the screen saver plugins are activated. Don't know what it is, will need to check this later.

**Comment by vineshsn** [comment]
This is working sometime. Not working many times. But the delay to call the blank screensaver is greatly reduced and it's fine.

**Comment by rsmoorthy** [comment]
Related to #30. It was fixed earlier on 07th Feb image, but then closed (revoked) based on #30

**Comment by rsmoorthy** [comment]
This is properly fixed in Pi patch 2019040401 and app version 1.0.10.

Now, we again, call the blank screensaver after play is stopped, play ended and play is paused. There is no delay now.
