### ISSUE TITLE
Updation of volumes information

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#60]
In Isha Pi app version 1.0.13.9 the list volumes mounted is not updating the currently mounted but the old values of the Pi.

**Comment by rsmoorthy** [comment]
I tested it like this and I did not find the problem:

App 1.0.13.9
Pi with Patch 2019040401

a) Connect -> And it shows Volumes Mounted
b) Then I moved the Pi with old patch 20190319
c) Pressed Connect again -> And it is (correctly) showing Volumes Mounted as none (because without the latest patch, it does not show the volumes mounted)

Can you help me if I have simulated it correctly?

**Comment by rsmoorthy** [comment]
Please retest this and let me know.
