### ISSUE TITLE
'No Credentials' on the home screen of the app

### ISSUE THREAD

**Issue by vineshsn** [rsmoorthy/ishapi#76]
1. 'No Credentials' status is displayed for a user who is given the valid credentials on the home screen of the app. Though it's not true and the encrypted volumes get mounted this message displayed is creating doubt for a first time user.
2. Instead of saying 'Waiting for volumes to be mounted..' if it says 'Mounting Volumes...' or 'volumes mounting...' it'll look fine..

**Comment by rsmoorthy** [comment]
Fixed in 1.0.17

1. No credentials might still appear briefly for 1-2 secs, as it takes 1-2 for the credentials to download. (When you logout and login, or when you login for the first time). Note: Whenever you logout, we remove all the keys from the mobile and needs to be downloaded from the server. 

Earlier, we did not try automatically. Now we automatically retry. Hence the "No Credentials" may appear for a very brief period. We retry 5 times now.

2. Changed the text.
